"""init

Revision ID: 1dbb3151603c
Revises: abfa4d5aa8a7
Create Date: 2026-03-16 17:00:45.528977

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dbb3151603c'
down_revision: Union[str, Sequence[str], None] = 'abfa4d5aa8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('weight', sa.Float(), nullable=False))
    op.add_column('shipment', sa.Column('estimated_delivery', sa.DateTime(), nullable=False))
    op.add_column('shipment', sa.Column('seller_id', sa.Uuid(), nullable=False))
    op.alter_column('shipment', 'content',
               existing_type=sa.CHAR(length=1),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.alter_column('shipment', 'status',
               existing_type=sa.CHAR(length=1),
               type_=sa.Enum('placed', 'delivered', 'in_transit', 'out_for_delivery', name='shipmentstatus'),
               existing_nullable=False,
               postgresql_using="status::text::shipmentstatus")
    op.create_foreign_key(None, 'shipment', 'seller', ['seller_id'], ['id'])
    op.drop_column('shipment', 'destination')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('destination', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.alter_column('shipment', 'status',
               existing_type=sa.Enum('placed', 'delivered', 'in_transit', 'out_for_delivery', name='shipmentstatus'),
               type_=sa.CHAR(length=1),
               existing_nullable=False)
    op.alter_column('shipment', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.CHAR(length=1),
               existing_nullable=False)
    op.drop_column('shipment', 'seller_id')
    op.drop_column('shipment', 'estimated_delivery')
    op.drop_column('shipment', 'weight')
    # ### end Alembic commands ###
