"""Devlivery Partner new

Revision ID: a6898f2ceb4e
Revises: 1443f64a5c91
Create Date: 2026-03-16 17:47:00.164200

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6898f2ceb4e'
down_revision: Union[str, Sequence[str], None] = '1443f64a5c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('seller', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('shipment', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment', 'created_at')
    op.drop_column('seller', 'created_at')
    op.drop_column('delivery_partner', 'created_at')
    # ### end Alembic commands ###
